[workspace]
resolver = "2"
members = [
    "crates/mhdn-rpc",
    "crates/mhdn-game",
    "crates/mhdn-proj",
    "crates/mhdn-platform",
    "crates/mhdn-render",
    "crates/mhdn-fx",
    "crates/mhdn-probe",
    "crates/mhdn-app",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/EsrgaN/mhdn"
rust-version = "1.75"

[workspace.dependencies]
thiserror = "2.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
