[package]
name = "mhdn-probe"
description = "CLI for reverse engineering: scan, watch, dump, record"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "mhdn-probe"
path = "src/main.rs"

[dependencies]
clap.workspace = true
mhdn-game = { path = "../mhdn-game" }
mhdn-rpc = { path = "../mhdn-rpc" }
thiserror.workspace = true
