[package]
name = "mhdn-platform"
description = "Host window tracking and transparent overlay window creation"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]

[dependencies]
raw-window-handle = "0.6.2"
thiserror.workspace = true
winit = "0.30.13"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10.1"
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = [
    "std",
    "libc",
    "objc2-core-foundation",
    "NSApplication",
    "NSColor",
    "NSResponder",
    "NSButton",
    "NSControl",
    "NSRunningApplication",
    "NSScreen",
    "NSStatusBar",
    "NSStatusBarButton",
    "NSStatusItem",
    "NSView",
    "NSWindow",
    "NSWorkspace",
] }
objc2-foundation = "0.3.2"
